# Generated by Django 3.2 on 2021-04-26 02:10

from django.db import migrations
import enumfields.fields
import player.enum


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerlevelsettings',
            name='start_at',
        ),
        migrations.AlterField(
            model_name='playerlevelsettings',
            name='state',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=2, enum=player.enum.PlayerState, help_text='Player game status.', verbose_name='State'),
        ),
    ]
