# Generated by Django 3.2 on 2021-04-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20210426_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_energy_update',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last energy update'),
        ),
        migrations.AddField(
            model_name='player',
            name='prev_energy',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Prev energy'),
        ),
        migrations.AddField(
            model_name='playerlevelsettings',
            name='start_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Start at'),
        ),
    ]
